# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reflections & Reviews
email: baliramkale12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This platform is dedicated to examining contemporary issues through context, history, and reason. It features essays, commentary, and reviews across politics, news, culture, and cinema, with a focus on depth, clarity, and critical inquiry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.in" # the base hostname & protocol for your site, e.g. http://example.com
author: Baliram Kale
contact_number: +91 7798336622

# Social Links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/baliram-kale
  - name: Instagram
    url: https://www.instagram.com/houseofthemigraines

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  posts:
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Baliram Kale"
  - scope:
      path: ""
    values:
      layout: "default"

# Reading Time
reading_time:
  strip_html: true
  words_per_minute: 200

# Site Navigation
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog.html
  - title: About
    url: /about.html
  - title: Contact
    url: /contact.html

# Categories
categories:
  - Politics
  - History
  - Governance
  - Youth & Society
  - Opinion / Editorial
